### ISSUE TITLE
chalk.hex() themes break format string padding

### ISSUE THREAD

**Issue by mpounsett** [bluenote10/yachalk#6]
```python
mystring = "foux"
width = 6
mycolour = "00ff00"
print(f"{mystring:>{width}}")

colour = chalk.hex(mycolour)
mystring = colour(mystring)
print(f"{mystring:>{width}}")
```

output should be:
```
  foux
  foux
```

... but is actually...
```
  foux
foux
```

**Comment by bluenote10** [comment]
That is a common problem with ANSI escape codes. They are actually part of the string, just not visible! So if you `colour` your string, it actually has increased its length, and so the width-based alignment has unexpected behavior. What you'll have to do is to either reverse the order of width-alignment and coloring like so:

![image](https://user-images.githubusercontent.com/3620703/134994514-fa5fef7c-c6c7-4993-bc9f-178ecef146c2.png)

Alternatively, if that is not possible, you would have to subtract the size increment due to ANSI escape codes from your target width.

**Comment by mpounsett** [comment]
Aha, this makes sense.  Thanks!
